version: '3'
services:
  zkui:
    image: qnib/zkui
    container_name: zkui
    environment:
      ZKUI_ZK_SERVER: ${ZOOKEEPER_SERVERS}
    ports:
      - 9090:9090
    volumes:
      - ./zkui/config.cfg:/opt/zkui/config.cfg
  zk1:
    image: 'zookeeper'
    restart: always
    container_name: zk1
    ports:
      - '2181:2181'
    volumes:
      - ./data/zookeeper1:/data
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: ${ZOO_SERVERS}
      ZOO_4LW_COMMANDS_WHITELIST: '*'
  zk2:
    image: 'zookeeper'
    restart: always
    container_name: zk2
    ports:
      - '2182:2181'
    volumes:
      - ./data/zookeeper2:/data
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: ${ZOO_SERVERS}
      ZOO_4LW_COMMANDS_WHITELIST: '*'
  zk3:
    image: 'zookeeper'
    restart: always
    container_name: zk3
    ports:
      - '2183:2181'
    volumes:
      - ./data/zookeeper3:/data
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: ${ZOO_SERVERS}
      ZOO_4LW_COMMANDS_WHITELIST: '*'

